### ISSUE TITLE
can't update org.jetbrains.kotlinx:kotlinx-coroutines-test to v1.4.2

### ISSUE THREAD

**Issue by miduch** [ologe/flow-test-observer#6]
Execution failed for task ':app:processDebugAndroidTestManifest'.
> Could not resolve all files for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.2.
     Required by:
         project :app
      > Cannot find a version of 'org.jetbrains.kotlinx:kotlinx-coroutines-test' that satisfies the version constraints:
           Dependency path 'ComposeVenues:app:unspecified' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.2'
           Constraint path 'ComposeVenues:app:unspecified' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-test:{strictly 1.4.1}' because of the following reason: debugRuntimeClasspath uses version 1.4.1
           **Dependency path 'ComposeVenues:app:unspecified' --> 'com.github.ologe:flow-test-observer:1.5.0' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.1'**

**Comment by ologe** [comment]
Hi @miduch, just tested on a sample app and it works. I think that happens because of your project setup.

Can you share a snippet from the `dependency` block from your application module? I am mostly interested to see which coroutines dependencies are you importing.
Also, are you on a multimodule project?

**Comment by miduch** [comment]
hi @ologe nope its not multiple project and this happens only when i try to run AndroidJUnit4 otherwise no issue. 

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.2"

    androidTestImplementation "androidx.arch.core:core-testing:2.1.0"
    androidTestImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.2" <--- this is issue , with 1.4.1 works fine 
    androidTestImplementation "com.github.ologe:flow-test-observer:1.5.0"
    androidTestImplementation "androidx.room:room-testing:2.2.6"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.3.0"
    androidTestImplementation "androidx.test.ext:junit:1.1.3-alpha02"

**Comment by ologe** [comment]
Unfortunately, even with your setup, I cannot reproduce the issues. 

However, I just published `1.5.1` that uses coroutines `1.4.2`. Let me know if this fixes it.

**Comment by miduch** [comment]
hi, sorry for late reply. 1.5.1 doesn't fix issue 

```
Execution failed for task ':app:processDebugAndroidTestManifest'.
> Could not resolve all files for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.2.
     Required by:
         project :app
         project :app > com.github.ologe:flow-test-observer:1.5.1
      > Cannot find a version of 'org.jetbrains.kotlinx:kotlinx-coroutines-test' that satisfies the version constraints:
           Dependency path 'ComposeVenues:app:unspecified' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.2'
           Constraint path 'ComposeVenues:app:unspecified' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-test:{strictly 1.4.1}' because of the following reason: debugRuntimeClasspath uses version 1.4.1
           Dependency path 'ComposeVenues:app:unspecified' --> 'com.github.ologe:flow-test-observer:1.5.1' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.2'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

maybe there is something wrong with org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.2 itself and not with com.github.ologe:flow-test-observer
